# Generated by Django 4.1 on 2022-08-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_blog_category_remove_order_orderdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='total',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
